Repository BulbProject/bulb-project-api, pull requests merged in 2020-06, with the labels that each got.

#42 refactor: Refactor do/calculation endpoint
  .eslintignore
  .eslintrc.json
  jest.config.js
  package.json
  src/controllers/do/calculation/algorithms/31500000-1/index.spec.ts
  src/controllers/do/calculation/algorithms/31500000-1/index.ts
  src/controllers/do/calculation/algorithms/31500000-1/types.d.ts
  src/controllers/do/calculation/algorithms/31500000-1/utils.ts
  src/controllers/do/calculation/index.ts
  src/controllers/do/calculation/types.d.ts
  src/controllers/do/specification/algorithms/31500000-1/index.ts
  src/json-schemas/available-variants.ts
  src/json-schemas/parts/criteria.ts
  src/json-schemas/parts/index.ts
  src/json-schemas/parts/metrics.ts
  src/json-schemas/parts/observations.ts
  src/json-schemas/parts/options.ts
  src/json-schemas/parts/requirement-responses.ts
  src/json-schemas/parts/value.ts
  src/json-schemas/primitives/array.ts
  src/json-schemas/primitives/mixed.ts
  src/models/category-version.ts
  src/ref-data/31500000-1.ts
  src/ref-data/index.ts
  src/routes/do.ts
  src/types/data/category/index.d.ts
  src/types/transactions/available-variants/index.d.ts
  src/types/transactions/requested-need/index.d.ts
  src/types/transport/available-variants-response.d.ts
  src/types/transport/index.d.ts
  src/types/transport/requested-need-payload.d.ts
  tsconfig.json
  yarn.lock
Labels: refactor

#43 Refactor specification controller
  src/controllers/do/calculation/algorithms/31500000-1/31500000-1.spec.ts
  src/controllers/do/calculation/algorithms/31500000-1/31500000-1.ts
  src/controllers/do/calculation/algorithms/31500000-1/index.ts
  src/controllers/do/specification/algorithms/31500000-1/31500000-1.spec.ts
  src/controllers/do/specification/algorithms/31500000-1/31500000-1.ts
  src/controllers/do/specification/algorithms/31500000-1/generate-document.ts
  src/controllers/do/specification/algorithms/31500000-1/images-data.json
  src/controllers/do/specification/algorithms/31500000-1/images-data.ts
  src/controllers/do/specification/algorithms/31500000-1/index.ts
  src/mocks/index.ts
  src/routes/specifications.ts
  src/utils.ts
  tsconfig.json
Labels: feat, refactor

#44 feat: add `buid` id validation for `manage`, replace `errorBuilder` with `RequestError` class
  package.json
  src/controllers/categories/categories-list-entity.ts
  src/controllers/categories/category-version.ts
  src/controllers/categories/versions-package.ts
  src/controllers/do/calculation/algorithms/31500000-1/31500000-1.ts
  src/controllers/do/calculation/index.ts
  src/controllers/do/specification/algorithms/31500000-1/31500000-1.ts
  src/controllers/do/specification/index.ts
  src/controllers/manage/activate-category.ts
  src/controllers/manage/add-category.ts
  src/controllers/manage/update-category.ts
  src/controllers/specifications/specification.ts
  src/json-schemas/primitives/mixed.ts
  src/lib/error-builder/index.ts
  src/lib/request-error/index.ts
  src/routes/categories.ts
  src/routes/do.ts
  src/routes/manage.ts
  src/utils.ts
  src/validation-schemas/category-add-body.ts
  yarn.lock
Labels: feat, refactor

#45 Specifications cleaner service
  .env.examle
  Dockerfile
  docker-compose.yml
  jest.config.js
  src/config.ts
  src/index.ts
  src/lib/db/methods/specifications.ts
  src/models/specification.ts
  src/services/index.ts
  src/services/specification-cleaner/index.ts
  src/services/specification-cleaner/specification-cleaner.service.ts
  src/services/specification-cleaner/specification-cleaner.spec.ts
Labels: feat
