Repository BulbProject/bulb-project-api, pull requests merged in 2020-03, with the labels that each got.

#1 feat: Add API interfaces
  src/api/data/category.d.ts
  src/api/data/classification.d.ts
  src/api/data/coefficient.d.ts
  src/api/data/conversion.d.ts
  src/api/data/criteria/criterion.d.ts
  src/api/data/criteria/index.d.ts
  src/api/data/criteria/requirement-group.d.ts
  src/api/data/criteria/requirement.d.ts
  src/api/data/index.d.ts
  src/api/data/item.d.ts
  src/api/data/options/index.d.ts
  src/api/data/options/option-details.d.ts
  src/api/data/options/option-group.d.ts
  src/api/data/options/option.d.ts
  src/api/data/options/options-to-combine.d.ts
  src/api/data/period.d.ts
  src/api/shared/data-type.ts
  src/api/shared/index.ts
  src/api/transactions/available-variants/index.d.ts
  src/api/transactions/available-variants/metric.d.ts
  src/api/transactions/available-variants/observation.d.ts
  src/api/transactions/available-variants/unit.d.ts
  src/api/transactions/available-variants/value.d.ts
  src/api/transactions/index.d.ts
  src/api/transactions/requested-need.d.ts
  src/api/transactions/requirement/index.d.ts
  src/api/transactions/requirement/organization-reference.d.ts
  src/api/transactions/requirement/requirement-reference.d.ts
  src/api/transactions/requirement/requirement-response.d.ts
  src/api/transport/category-package.d.ts
  src/api/transport/category-version.d.ts
  src/api/transport/index.d.ts
Labels: enhancement

#5 Skeleton for work with category version in DB
  .eslintrc.json
  src/controllers/categoryVersion.ts
  src/controllers/index.ts
  src/index.ts
  src/lib/db/index.ts
  src/models/categoryVersion.ts
  src/models/index.ts
  src/routes/categories.ts
  src/routes/manage.ts
  src/types/data/category.d.ts
  src/types/data/classification.d.ts
  src/types/data/coefficient.d.ts
  src/types/data/conversion.d.ts
  src/types/data/criteria/criterion.d.ts
  src/types/data/criteria/index.d.ts
  src/types/data/criteria/requirement-group.d.ts
  src/types/data/criteria/requirement.d.ts
  src/types/data/index.d.ts
  src/types/data/item.d.ts
  src/types/data/options/index.d.ts
  src/types/data/options/option-details.d.ts
  src/types/data/options/option-group.d.ts
  src/types/data/options/option.d.ts
  src/types/data/options/options-to-combine.d.ts
  src/types/data/period.d.ts
  src/types/shared/data-type.ts
  src/types/shared/index.ts
  src/types/transactions/available-variants/index.d.ts
  src/types/transactions/available-variants/metric.d.ts
  src/types/transactions/available-variants/observation.d.ts
  src/types/transactions/available-variants/unit.d.ts
  src/types/transactions/available-variants/value.d.ts
  src/types/transactions/index.d.ts
  src/types/transactions/requested-need.d.ts
  src/types/transactions/requirement/index.d.ts
  src/types/transactions/requirement/organization-reference.d.ts
  src/types/transactions/requirement/requirement-reference.d.ts
  src/types/transactions/requirement/requirement-response.d.ts
  src/types/transport/category-package.d.ts
  src/types/transport/category-version.d.ts
  src/types/transport/index.d.ts
  tsconfig.json
Labels: enhancement

#6 feat(Models, Controllers, Routes): Add versions package functionality
  .env.examle
  src/config.ts
  src/controllers/categoryVersion.ts
  src/controllers/index.ts
  src/controllers/versionsPackage.ts
  src/models/categoryVersion.ts
  src/models/index.ts
  src/models/versionsPackage.ts
  src/routes/categories.ts
  src/routes/manage.ts
  src/types/transport/index.d.ts
  src/types/transport/versions-package.d.ts
  tsconfig.json
Labels: enhancement

#7 Categories list entity model
  src/controllers/categoriesListEntity.ts
  src/controllers/index.ts
  src/models/categoriesListEntity.ts
  src/models/index.ts
  src/routes/categories.ts
  src/routes/manage.ts
  src/types/transport/categories-list-entity.d.ts
  src/types/transport/index.d.ts
Labels: enhancement

#8 refactor(Routes): Refactor routes
  src/routes/action.ts
  src/routes/categories.ts
  src/routes/do.ts
  src/routes/index.ts
  src/routes/manage.ts
  src/routes/specification.ts
Labels: refactor

#10 feat: Add functionality add category
  .eslintrc.json
  package.json
  src/controllers/categoriesListEntity.ts
  src/controllers/categoryVersion.ts
  src/controllers/index.ts
  src/controllers/versionsPackage.ts
  src/models/categoryVersion.ts
  src/models/versionsPackage.ts
  src/routes/manage.ts
  src/utils.ts
  src/validation-schemas/categoryAddBody.ts
  src/validation-schemas/index.ts
  tsconfig.json
  yarn.lock
Labels: feat
